name: Deployment Script

on:
  push:
    branches: [ dev22 ]
  pull_request:
    branches: [ dev22 ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: app
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}